# SPDX-FileCopyrightText: 2026 Alejandro Reyes-Consuelo
# SPDX-License-Identifier: MIT

"""tools/derive_register_totals.py - Derive the register's Totals block from
its rows, and compare it with the committed one.

The register's totals are a derived snapshot regenerated by hand each wave,
and the hand has now been measured wrong three times: the wave-12 stale
snapshot (repaired at `6e0bf7b`), wave 14a's mis-correction at `bb428b0`
(which "fixed" an F-09 miscount the committed block did not have, and wrote
a real one in — carried through ten regenerations to wave 15b), and the
prose around the table going stale independently of it. F-131's fix cell
names this tool: parse the table, derive the block, assert. A derivation
from the rows is the only check that does not compare one hand count
against the previous hand count.

The derivation implements the register's own counting rules
(03_findings.md, "How this register is counted"):

  - a row begins ``| **F-nn**`` — count rows, never the maximum ID
    (the register has a permanent three-ID gap at F-56/F-57/F-58);
  - cells split on unescaped pipes only (``(?<!\\)|``) — an unescaped pipe
    inside a cell once pushed a row's ``(done)`` marker out of its column
    (F-153), so a row that does not split into exactly eight cells is an
    ERROR here, not a guess;
  - the severity is the LAST bolded severity in the cell, so a revised
    cell (``**Medium** → **High**``) counts at its post-arrow value; prose
    mentions of severities are never bolded and never counted;
  - status is the marker in the Effort cell and nothing else: ``(done)``
    is closed; ``(scheduled)``, ``(backlog)``, ``(parked)`` and no marker
    are the four kinds of open.

Usage:
    python tools/derive_register_totals.py            # compare, report
    python tools/derive_register_totals.py --print    # print derived block

Exit code: 0 when the committed block equals the derived one in all 40
cells and every row parses; 1 otherwise. Suitable as a pre-commit gate
beside `pytest -q`, and `tests/test_register_totals.py` runs the same
comparison inside the suite, so a drifted block is a red suite.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REGISTER = Path(__file__).resolve().parents[1] / "docs" / "internal" \
    / "diagnostic" / "03_findings.md"

SEVERITIES = ("Critical", "High", "Medium", "Low")
#: The Effort-cell status vocabulary is a closed set. ``(done)`` closes a
#: row; the other three are open-with-a-decision; no marker is open.
OPEN_BUCKETS = ("unscheduled", "scheduled", "backlog", "parked")

_ROW_RE = re.compile(r"^\|\s*\*\*F-\d+\*\*\s*\|")
_CELL_SPLIT = re.compile(r"(?<!\\)\|")
_BOLD_SEV = re.compile(r"\*\*(Critical|High|Medium|Low)\*\*")
_BLOCK_ROW = re.compile(
    r"^\|\s*\*\*(Critical|High|Medium|Low|Total)\*\*\s*\|(.+)$")


class RegisterParseError(ValueError):
    """A row that cannot be counted must stop the count, not skew it."""


def derive(text: str):
    """The Totals block derived from the rows.

    Returns ``{severity: [total, closed, open, unscheduled, scheduled,
    backlog, parked]}`` with a ``"Total"`` key summing the four.
    """
    block = {s: [0] * 7 for s in SEVERITIES}
    for line in text.splitlines():
        if not _ROW_RE.match(line):
            continue
        cells = _CELL_SPLIT.split(line)[1:-1]
        if len(cells) != 8:
            fid = re.search(r"F-\d+", cells[0] if cells else line).group(0)
            raise RegisterParseError(
                "%s splits into %d cells against an eight-column header - "
                "an unescaped pipe inside a cell (F-153's shape), or a "
                "malformed row" % (fid, len(cells)))
        bold = _BOLD_SEV.findall(cells[1])
        if not bold:
            fid = re.search(r"F-\d+", cells[0]).group(0)
            raise RegisterParseError(
                "%s carries no bolded severity in its severity cell" % fid)
        sev = bold[-1]          # post-arrow: the last bolded value wins
        effort = cells[-1]
        row = block[sev]
        row[0] += 1
        if "(done)" in effort:
            row[1] += 1
            continue
        row[2] += 1
        if "(scheduled)" in effort:
            row[4] += 1
        elif "(backlog)" in effort:
            row[5] += 1
        elif "(parked)" in effort:
            row[6] += 1
        else:
            row[3] += 1
    total = [sum(block[s][i] for s in SEVERITIES) for i in range(7)]
    block["Total"] = total
    return block


def committed(text: str):
    """The Totals block as committed, ``{severity: [seven numbers]}``.

    Reads the first markdown table whose leading cell is a bolded severity
    or **Total** — the register carries exactly one such table.
    """
    out = {}
    for line in text.splitlines():
        m = _BLOCK_ROW.match(line)
        if not m:
            continue
        label = m.group(1)
        if label in out:        # a second table would be a new defect
            raise RegisterParseError(
                "the severity label %r appears in two table rows" % label)
        nums = [int(n) for n in re.findall(r"\d+", m.group(2))]
        if len(nums) != 7:
            raise RegisterParseError(
                "the committed %r row carries %d numbers, not 7"
                % (label, len(nums)))
        out[label] = nums
    missing = [s for s in SEVERITIES + ("Total",) if s not in out]
    if missing:
        raise RegisterParseError(
            "no committed Totals row found for: %s" % ", ".join(missing))
    return out


def compare(text: str):
    """Every cell where the committed block disagrees with the derived one.

    Returns a list of ``(severity, column, committed, derived)`` tuples —
    empty means the block is exact.
    """
    d, c = derive(text), committed(text)
    cols = ("Total", "Closed", "Open") + OPEN_BUCKETS
    diffs = []
    for sev in SEVERITIES + ("Total",):
        for i, col in enumerate(cols):
            if c[sev][i] != d[sev][i]:
                diffs.append((sev, col, c[sev][i], d[sev][i]))
    return diffs


def _format(block) -> str:
    lines = ["| Severity | Total | Closed | **Open** | — of which "
             "unscheduled | scheduled | backlog | parked |",
             "|---|---:|---:|---:|---:|---:|---:|---:|"]
    for sev in SEVERITIES:
        r = block[sev]
        lines.append("| **%s** | %d | %d | **%d** | %d | %d | %d | %d |"
                     % (sev, *r))
    t = block["Total"]
    lines.append("| **Total** | **%d** | **%d** | **%d** | %d | %d | %d "
                 "| %d |" % (t[0], t[1], t[2], t[3], t[4], t[5], t[6]))
    return "\n".join(lines)


def main(argv) -> int:
    text = REGISTER.read_text(encoding="utf-8")
    if "--print" in argv:
        print(_format(derive(text)))
        return 0
    try:
        diffs = compare(text)
    except RegisterParseError as e:
        print("PARSE ERROR: %s" % e)
        return 1
    if not diffs:
        print("Totals block matches the rows in all 40 cells.")
        return 0
    print("Totals block DIVERGES from the rows in %d cell(s):" % len(diffs))
    for sev, col, com, der in diffs:
        print("  %-8s %-12s committed=%d derived=%d" % (sev, col, com, der))
    print("\nDerived block to paste:\n\n%s" % _format(derive(text)))
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
